In [ ]:
x = np.array([[1,3,5,9],[2,4,6,8]])
y = np.array([[1.4,5,6.2,7],[9.9,8.2,6,4.1]])
print(x.dtype)
print(y.dtype)

int64
float64


In [ ]:
import numpy as np

In [ ]:
print(x+2)    #Sum in Numpy

[[ 3  5  7 11]
 [ 4  6  8 10]]


In [ ]:
print(x**2)

[[ 1  9 25 81]
 [ 4 16 36 64]]


In [ ]:
x.shape

(2, 4)

In [ ]:
x.ndim

2

In [ ]:
x.itemsize

8

In [ ]:
x.size

8

In [ ]:
type(x)
type(y)

numpy.ndarray

In [ ]:
np.zeros((5, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones( (4,2,3), dtype=np.int16 )

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [ ]:
np.empty( (4,3) ) 

array([[3.46699065e-316, 2.47032823e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 1.58817677e-052],
       [5.28445254e-091, 1.04049503e-042, 1.00552081e-047],
       [1.57252062e-076, 3.99910963e+252, 1.46030983e-319]])

In [ ]:
 np.arange( 5, 6, 9 )  

array([5])

In [ ]:
np.arange(0,2,.3)  

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [ ]:
from numpy import pi
np.linspace( 0, 3, 6 )

array([0. , 0.6, 1.2, 1.8, 2.4, 3. ])

In [ ]:
z = np.linspace( 0, 3*pi, 25 )
print(z)

[0.         0.39269908 0.78539816 1.17809725 1.57079633 1.96349541
 2.35619449 2.74889357 3.14159265 3.53429174 3.92699082 4.3196899
 4.71238898 5.10508806 5.49778714 5.89048623 6.28318531 6.67588439
 7.06858347 7.46128255 7.85398163 8.24668072 8.6393798  9.03207888
 9.42477796]


In [ ]:
 z = np.arange(30).reshape(6,5) 
 print(z)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [ ]:
u = np.arange(90).reshape(3,5,6) 
print(u)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]]

 [[60 61 62 63 64 65]
  [66 67 68 69 70 71]
  [72 73 74 75 76 77]
  [78 79 80 81 82 83]
  [84 85 86 87 88 89]]]


In [ ]:
print(np.arange(100000))

[    0     1     2 ... 99997 99998 99999]


In [ ]:
print(np.arange(100000).reshape(1000,100))

[[    0     1     2 ...    97    98    99]
 [  100   101   102 ...   197   198   199]
 [  200   201   202 ...   297   298   299]
 ...
 [99700 99701 99702 ... 99797 99798 99799]
 [99800 99801 99802 ... 99897 99898 99899]
 [99900 99901 99902 ... 99997 99998 99999]]


In [ ]:
25*np.cos(x)

array([[ 13.50755765, -24.74981242,   7.09155464, -22.77825655],
       [-10.40367091, -16.34109052,  24.00425717,  -3.63750085]])

In [ ]:
x>3

array([[False, False,  True,  True],
       [False,  True,  True,  True]])

In [ ]:
s = np.array([[1,3],[2,4]])
t = np.array([[5,2],[1,9]])
s@t

array([[ 8, 29],
       [14, 40]])

In [ ]:
s.dot(t)  

array([[ 8, 29],
       [14, 40]])

In [ ]:
rb = np.random.default_rng(1)
d = rb.random((2,3))
print(d)

[[0.51182162 0.9504637  0.14415961]
 [0.94864945 0.31183145 0.42332645]]


In [ ]:
d *= 2
print(d)


[[3.07092975 5.70278218 0.86495768]
 [5.69189668 1.87098871 2.53995869]]


In [ ]:
sum(d) 

array([8.76282643, 7.57377089, 3.40491637])

In [ ]:
d.sum()

19.741513691196786

In [ ]:
d.min()

0.8649576763178024

In [ ]:
d.max()

5.702782177955612

In [ ]:
x
x.sum(axis=0)

array([ 3,  7, 11, 17])

In [ ]:
y.sum(axis=1)

array([19.6, 28.2])

In [ ]:
x.cumsum(axis=1)

array([[ 1,  4,  9, 18],
       [ 2,  6, 12, 20]])

In [ ]:
z = np.arange(10).reshape(2,-1)
print(z)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
za = np.repeat(1, 10).reshape(2,-1)
print(za)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
np.concatenate([z, za], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
np.hstack([z, za])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5

5

In [ ]:
np.random.seed(100)
rand_z = np.random.random([3,3])/1e3
rand_z

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

In [ ]:
np.set_printoptions(threshold=6)
sa = np.arange(15)
sa


array([ 0,  1,  2, ..., 12, 13, 14])

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_data = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris_data

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d1 = np.genfromtxt(url, delimiter=',', dtype=None)
iris_1d1

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'), ...,
       (6.5, 3. , 5.2, 2. , b'Iris-virginica'),
       (6.2, 3.4, 5.4, 2.3, b'Iris-virginica'),
       (5.9, 3. , 5.1, 1.8, b'Iris-virginica')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [ ]:
spec = np.array([row[4] for row in iris_1d1])
spec[:5]

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d1 = np.genfromtxt(url, delimiter=',', dtype=None)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris2 = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
iris2

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

In [ ]:
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

# Solution
Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)
# or 
S = (sepallength - Smin)/sepallength.ptp()  # Thanks, David Ojeda!
print(S)

[0.22222222 0.16666667 0.11111111 ... 0.61111111 0.52777778 0.44444444]


In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([float(row[0]) for row in iris])

# Solution
def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)
    print(softmax(sepallength))

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

# Method 1
i, j = np.where(iris_2d)
iris_2d

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

In [ ]:
np.random.seed(100)
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
print(iris_2d[:9])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 ...
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' nan b'1.4' b'0.2' b'Iris-setosa']]


In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 5
Position of missing values: 
 (array([ 38,  80, 106, 113, 121]),)


In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)
iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

# Solution
# No direct numpy function for this.
# Method 1:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_nan_in_row][:4]


array([[4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

# Solution 1
np.corrcoef(iris[:, 0], iris[:, 2])[0, 1]


0.8717541573048718

In [ ]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.isnan(iris_2d).any()

False

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

species = iris[:, 4]
species

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype=object)

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
np.argwhere(iris[:, 3].astype(float) > 1.0)[0]

array([50])

In [ ]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
np.clip(a, a_min=10, a_max=30)

array([27.62684215, 14.64009987, 21.80136195, ..., 10.        ,
       30.        , 14.42961361])

In [ ]:
a = np.random.uniform(1,50, 20)
print(a.argsort())

[ 6  9 14 ... 18  1 16]


In [ ]:
rr = np.random.randint(1,11,size=(6, 10))
rr

array([[ 2,  6,  5, ...,  1, 10,  4],
       [ 7,  4,  5, ...,  1,  5,  5],
       [ 6,  8,  7, ...,  8,  2,  7],
       [ 7,  1,  8, ...,  3,  5,  4],
       [ 8, 10,  1, ...,  7,  6,  7],
       [ 5,  8,  4, ...,  8,  2,  6]])

In [ ]:
rr1 = np.arange(3)
rr2 = np.arange(3,7)
rr3 = np.arange(7,10)

array_of_arrays = np.array([rr1, rr2, rr3])
array_of_arrays

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """


array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])],
      dtype=object)

In [ ]:
np.random.seed(101) 
rr = np.random.randint(1,4, size=6)
rr

array([2, 3, 2, 2, 2, 1])

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', ..., 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', ..., 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica'], dtype='<U15')

In [ ]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)

[[ 9  4 15  0 17]
 [16 17  8  9  0]]


In [ ]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)
# Method 1
moving_average(Z, n=3).round(2)

array:  [8 8 3 ... 2 5 2]


array([6.33, 6.  , 5.67, ..., 2.  , 3.67, 3.  ])

In [ ]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)

['2018-02-01' '2018-02-03' '2018-02-05' ... '2018-02-19' '2018-02-21'
 '2018-02-23']
